version: '3.8'

services:
  web-assistant:
    build: .
    container_name: game_words
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./models:/app/models
    # Если у тебя NVIDIA и ты хочешь GPU в докере, добавь эти строки:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - PYTHONUNBUFFERED=1
